# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7582742eac21093fd7e04e2aa5ced5d9b6970885228334c0e2c2174e0cb632c3d1e8788bb2d612042ce3b8756ee251eedd9b4382892cd3172f99eee451edec52

test:
  secret_key_base: 459b305e9998cf4effc52f8dcadb859462324a651001302e404c03a5010a670cbb260a494349f44cc741ed7df0929a762db032f52d6c641a2b916220657d40f1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
